// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByY1b4rSFPCOP6o_uh1OTweegMN17FP2g',
    appId: '1:894725618175:android:d13f73a018c5770e088fca',
    messagingSenderId: '894725618175',
    projectId: 'meal-dash-72a04',
    databaseURL: 'https://meal-dash-72a04-default-rtdb.firebaseio.com',
    storageBucket: 'meal-dash-72a04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC48SDu2PyQ-BneDzREwQGxzND96pO5u6Y',
    appId: '1:894725618175:ios:6f9dec5556adc63b088fca',
    messagingSenderId: '894725618175',
    projectId: 'meal-dash-72a04',
    databaseURL: 'https://meal-dash-72a04-default-rtdb.firebaseio.com',
    storageBucket: 'meal-dash-72a04.firebasestorage.app',
    androidClientId: '894725618175-vsldqt3u23m56k3k5ah2lc5rlpc1o6g0.apps.googleusercontent.com',
    iosClientId: '894725618175-5m7hvifnb5um7b6sa069l4o84cn5blh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartoonApp',
  );
}
